### ISSUE TITLE
README

### ISSUE THREAD

**Issue by webflo** [webflo/config_file_import#1]
Config file in config/files/files.yml
Image in config/files/embed_buttons/snippet.png

```
files:
  -
    path: 'embed_buttons/snippet.png'
    uuid: 7c964e8c-790e-49b1-9bf9-370cba1e5591
```

Command: drush config-file-import ../config/files/files.yml
